/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadenas;

import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author Manuel
 */
public class Lector extends javax.swing.JFrame {

    /**
     * Creates new form Lector
     * 
     */
    
    
    public Lector() {
        initComponents();
        
    }

        public void CadenasCar(){
            String mayusculas = "";
        }
    
      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonAnalizar = new javax.swing.JButton();
        BotonEjemplo = new javax.swing.JButton();
        BotonLimpieza = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxt1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxt2 = new javax.swing.JTextArea();
        jLbl3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jItem1 = new javax.swing.JMenuItem();
        jItem2 = new javax.swing.JMenuItem();
        jItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Texto a Analizar:");

        jLabel2.setText("Datos extraidos:");

        BotonAnalizar.setText("¡Analizar!");
        BotonAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnalizarActionPerformed(evt);
            }
        });

        BotonEjemplo.setText("Ejemplo");
        BotonEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEjemploActionPerformed(evt);
            }
        });

        BotonLimpieza.setText("Limpiar");
        BotonLimpieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiezaActionPerformed(evt);
            }
        });

        jTxt1.setColumns(20);
        jTxt1.setRows(5);
        jScrollPane1.setViewportView(jTxt1);

        jTxt2.setColumns(20);
        jTxt2.setRows(5);
        jScrollPane2.setViewportView(jTxt2);

        jLbl3.setText("Errores:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jMenu1.setText("Archivo");

        jItem1.setText("Cargar Archivo");
        jItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jItem1);

        jItem2.setText("Guardar Archivo");
        jMenu1.add(jItem2);

        jItem3.setText("Salir");
        jMenu1.add(jItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jItem12.setText("Acerca De");
        jMenu2.add(jItem12);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLbl3))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonAnalizar)
                .addGap(41, 41, 41)
                .addComponent(BotonEjemplo)
                .addGap(55, 55, 55)
                .addComponent(BotonLimpieza)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonLimpieza)
                    .addComponent(BotonEjemplo)
                    .addComponent(BotonAnalizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonLimpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiezaActionPerformed
        String limpio = " ";
        
        jTxt1.append(limpio);
        jTxt2.append(limpio);
    }//GEN-LAST:event_BotonLimpiezaActionPerformed

    private void BotonEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEjemploActionPerformed
        String chain = "Program;  "
                + " ;var char ejemplo;  "
                + " ;El objeto leido debe salir aquí;";
        String cadena = chain;
         
        
                jTxt1.append(cadena);
    }//GEN-LAST:event_BotonEjemploActionPerformed

    private void BotonAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnalizarActionPerformed
        String cadena = null;
        String cadenaAnalizada = null;
        cadena = jTxt1.getText();
        ArrayList<Character> chars = new ArrayList();
        for (int i = 0; i<cadena.length(); i++ ){
            chars.add(cadena.charAt(i));
            if((chars.get(i).equals("A"))||(chars.get(i).equals("B"))||(chars.get(i).equals("C"))||(chars.get(i).equals("D"))||(chars.get(i).equals("E"))||(chars.get(i).equals("F"))||(chars.get(i).equals("H"))||(chars.get(i).equals("I"))||(chars.get(i).equals("J"))||(chars.get(i).equals("K"))||(chars.get(i).equals("L"))||(chars.get(i).equals("M"))||(chars.get(i).equals("N"))||(chars.get(i).equals("O"))||(chars.get(i).equals("P"))||(chars.get(i).equals("Q"))||(chars.get(i).equals("R"))||(chars.get(i).equals("S"))||(chars.get(i).equals("T"))||(chars.get(i).equals("U"))||(chars.get(i).equals("V"))||(chars.get(i).equals("W"))||(chars.get(i).equals("X"))||(chars.get(i).equals("Y"))||(chars.get(i).equals("Z"))){
                System.out.println("Es una mayúscula");
            }
           if((chars.get(i).equals("a"))||(chars.get(i).equals("b"))||(chars.get(i).equals("c"))||(chars.get(i).equals("d"))||(chars.get(i).equals("e"))||(chars.get(i).equals("f"))||(chars.get(i).equals("g"))||(chars.get(i).equals("h"))||(chars.get(i).equals("i"))||(chars.get(i).equals("j"))||(chars.get(i).equals("k"))||(chars.get(i).equals("l"))||(chars.get(i).equals("m"))||(chars.get(i).equals("n"))||(chars.get(i).equals("o"))||(chars.get(i).equals("p"))||(chars.get(i).equals("q"))||(chars.get(i).equals("r"))||(chars.get(i).equals("s"))||(chars.get(i).equals("t"))||(chars.get(i).equals("u"))||(chars.get(i).equals("v"))||(chars.get(i).equals("w"))||(chars.get(i).equals("x"))||(chars.get(i).equals("y"))||(chars.get(i).equals("z"))){
                System.out.println("Son minúsculas");
           }
            if((chars.get(i).equals("0"))||(chars.get(i).equals("1"))||(chars.get(i).equals("2"))||(chars.get(i).equals("3"))||(chars.get(i).equals("4"))||(chars.get(i).equals("5"))||(chars.get(i).equals("6"))||(chars.get(i).equals("7"))||(chars.get(i).equals("8"))||(chars.get(i).equals("9"))){
                System.out.println("Son números");
            }
        else{
               System.out.println("Caracter no reconocido");
           }
    }//GEN-LAST:event_BotonAnalizarActionPerformed
    }
    private void jItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAnalizar;
    private javax.swing.JButton BotonEjemplo;
    private javax.swing.JButton BotonLimpieza;
    private javax.swing.JMenuItem jItem1;
    private javax.swing.JMenuItem jItem12;
    private javax.swing.JMenuItem jItem2;
    private javax.swing.JMenuItem jItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLbl3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTxt1;
    private javax.swing.JTextArea jTxt2;
    // End of variables declaration//GEN-END:variables
}
